CXXFLAGS                +=
install_dir              = /usr/local
python_dir               =
swig_lib_flags_apple     = -bundle -flat_namespace -undefined suppress
swig_lib_flags_linux     = -shared
swig_lib_flags           =
